### ISSUE TITLE
Compressed Chest trying to use client side class on server side

### ISSUE THREAD

**Issue by Sir-Will** [WanionCane/Avaritiaddons#6]
```
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
    at wanion.avaritiaddons.block.chest.compressed.TileEntityCompressedChest.getDefaultInventoryName(TileEntityCompressedChest.java:31) ~[TileEntityCompressedChest.class:?]
    at wanion.avaritiaddons.block.chest.TileEntityAvaritiaddonsChest.func_145825_b(TileEntityAvaritiaddonsChest.java:193) ~[TileEntityAvaritiaddonsChest.class:?]
    at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftInventory.getTitle(CraftInventory.java:427) ~[CraftInventory.class:1.7.10-1614.MyM.4]
    at net.aufdemrand.denizen.objects.dInventory.mirrorBukkitInventory(dInventory.java:45) ~[?:?]
    at net.aufdemrand.denizen.scripts.containers.core.WorldScriptHelper.inventoryClickEvent(WorldScriptHelper.java:2629) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor229.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.MyM.4]
    ... 13 more
```

**Comment by WanionCane** [comment]
are you using forge?
because there are a lot of "bukkit" in your log.

**Comment by Sir-Will** [comment]
Cauldron -> forge + bukkit

**Comment by WanionCane** [comment]
this issue is not happening on forge, but, I am going to take a look on it anyway.

**Comment by WanionCane** [comment]
could you try wit this, please? [Avaritiaddons-1.2b](https://github.com/WanionCane/Avaritiaddons/releases/tag/1.2b)

**Comment by steelshot** [comment]
Have you tried Thermos, KCauldron has not been updated for 3 months and seems that Thermos is kindof being updated(23 days) http://cyberdynecc.github.io/Thermos/ ?

**Comment by Sir-Will** [comment]
@WanionCane  that fixed it, thanks.
